import { chromium } from '@playwright/test';
import fs from 'fs';
const URL = process.env.SUPABASE_URL || 'https://lrktftnalrtvaazaauhj.supabase.co';
const ANON = process.env.SUPABASE_ANON_KEY || '';
const PWD = (fs.readFileSync('.test-creds.env', 'utf8').match(/^SUPABASE_TEST_PASSWORD=(.*)$/m) || [])[1] || '';
const b = await chromium.launch();
const page = await b.newPage();
page.on('response', r => { if (r.status() >= 400) console.log('HTTP', r.status(), r.request().method(), r.url().slice(0, 100)); });
page.on('pageerror', e => console.log('PAGEERR', e.message));
page.on('console', m => { if (m.type() === 'error') console.log('CONSOLE', m.text().slice(0, 200)); });

await page.goto('http://localhost:3000/');
await page.fill('#cfg_url', URL); await page.fill('#cfg_key', ANON); await page.click('#cfg_save');
await page.click('[data-tab="signup"]');
const email = 'dbgo' + Date.now() + '@gmail.com';
await page.fill('#au_name', 'QA'); await page.fill('#au_email2', email); await page.fill('#au_pw2', PWD); await page.click('#au_signup_btn');
await page.waitForTimeout(2500);
await page.goto('http://localhost:3000/#/omr/templates/new');
await page.fill('#t_name', 'DBGO OMR ' + Date.now()); await page.fill('#t_q', '10'); await page.click('#t_save');
await page.waitForTimeout(1500);
console.log('template rows:', await page.evaluate(() => document.querySelectorAll('table.data-table tbody tr').length));
await page.goto('http://localhost:3000/#/papers/new');
await page.waitForSelector('#p_exam option:nth-child(2)', { state: 'attached' });
await page.selectOption('#p_exam', { index: 1 }); await page.fill('#p_count', '5'); await page.click('#gen_btn');
await page.waitForTimeout(4000);
console.log('gen_result text =', (await page.locator('#gen_result').innerText().catch(() => 'NONE')).slice(0, 200));
console.log('gen_result html =', await page.evaluate(() => { const e = document.querySelector('#gen_result'); return e ? e.innerHTML.slice(0, 200) : 'NO ELEMENT'; }));
await page.waitForSelector('#gen_result a', { timeout: 5000 }).catch(() => console.log('no link'));
await page.goto('http://localhost:3000/#/omr/sheets/new');
await page.waitForSelector('#s_paper option:nth-child(2)', { state: 'attached' });
const label = (await page.locator('#s_paper option').nth(1).textContent()).trim();
console.log('paper label =', label);
await page.selectOption('#s_paper', { label }); await page.fill('#s_roll', 'ROLL-1'); await page.click('#s_gen');
await page.waitForTimeout(4000);
console.log('url after s_gen =', page.url());
console.log('eval_btn present =', await page.locator('#eval_btn').count());
console.log('body snippet =', (await page.locator('#ep_main').innerText()).slice(0, 200).replace(/\n/g, ' '));
await b.close();
